<%@ Page Title="" Language="C#" MasterPageFile="~/Principal.Master" AutoEventWireup="true" CodeBehind="DetalledeCompra.aspx.cs" Inherits="Vistas.DetalledeCompra" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            font-size: x-large;
        }
        .auto-style2 {
            font-size: x-large;
            text-align: center;
        }
        .auto-style3 {
            font-size: small;
            text-align: center;
            margin-left: 0;
        }
        .auto-style4 {
            font-size: medium;
            text-align: left;
            width: 412px;
        }
        .auto-style5 {
            font-size: medium;
            text-align: left;
            width: 288px;
        }
        .auto-style6 {
            font-size: small;
        }
        .auto-style7 {
            font-size: medium;
        }
        .auto-style8 {
            font-size: medium;
            font-weight: normal;
        }
        .auto-style9 {
            font-size: small;
            text-align: left;
            width: 288px;
        }
        .auto-style13 {
            font-size: x-small;
        }
        .auto-style14 {
            text-align: left;
            width: 288px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="contenido" runat="server">
    <p class="auto-style1">
        <strong class="auto-style14" style="font-weight: bold">Asientos</strong></p>
    <p class="auto-style2">
        <asp:Image ID="imgAsientos" runat="server" Height="310px" ImageUrl="~/imagenes/asientos.jpg" ViewStateMode="Disabled" Width="370px" />
    </p>
    <table class="w-100">
        <tr>
            <td class="auto-style4">Seleccione su/s asiento/s:</td>
            <td class="auto-style5">
                &nbsp;
                <asp:DropDownList ID="ddlAsiento" runat="server" CssClass="auto-style18" DataSourceID="SqlDataSourceAsientosDisponibles" DataTextField="ID_Asiento" DataValueField="ID_Asiento" Height="19px" Width="201px">
                </asp:DropDownList>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </td>
            <td>
                <asp:Button ID="btnSeleccionar" runat="server" CssClass="auto-style3" Text="Seleccionar" />
            </td>
        </tr>
    </table>
    <br />
    <span __designer:mapid="282" class="auto-style18" style="font-size: medium">Asientos seleccionados: 
    <br />
                <asp:GridView ID="gvAsientos" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataSourceID="SqlDataSourceAsientosReservados" ForeColor="Black" GridLines="Horizontal" Width="280px" HorizontalAlign="Center" CssClass="auto-style6" Font-Size="X-Small">
                    <Columns>
                        <asp:BoundField DataField="ID_Asiento_FSA" HeaderText="ID Asiento" SortExpression="ID_Asiento_FSA" >
                        <FooterStyle Font-Bold="False" Font-Size="Small" />
                        <ItemStyle Font-Size="Small" HorizontalAlign="Center" />
                        </asp:BoundField>
                    </Columns>
                    <EditRowStyle HorizontalAlign="Center" Wrap="True" />
                    <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                    <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" HorizontalAlign="Center" />
                    <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                    <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F7F7F7" />
                    <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                    <SortedDescendingCellStyle BackColor="#E5E5E5" />
                    <SortedDescendingHeaderStyle BackColor="#242121" />
                    <RowStyle HorizontalAlign="Center" />
                </asp:GridView>
    <br />
    </span><span __designer:mapid="282" class="auto-style18">
    <span class="auto-style9" style="font-weight: bold"><span class="auto-style1">Promociones</span><span class="auto-style15" style="font-size: medium"><br />
        <asp:ListView ID="lvPromociones" runat="server" DataKeyNames="ID_Promocion" DataSourceID="SqlDataSourcePromociones" GroupItemCount="5" style="position: relative; font-size: 62%;">
            <EditItemTemplate>
                <td runat="server" style="background-color:#008A8C;color: #FFFFFF;" aria-expanded="true" aria-selected="undefined">ID_Promocion:
                    <asp:Label ID="ID_PromocionLabel1" runat="server" Text='<%# Eval("ID_Promocion") %>' />
                    <br />Estado_Promocion:
                    <asp:TextBox ID="Estado_PromocionTextBox" runat="server" Text='<%# Bind("Estado_Promocion") %>' />
                    <br />Nombre_Promocion:
                    <asp:TextBox ID="Nombre_PromocionTextBox" runat="server" Text='<%# Bind("Nombre_Promocion") %>' />
                    <br />Descripcion_Promocion:
                    <asp:TextBox ID="Descripcion_PromocionTextBox" runat="server" Text='<%# Bind("Descripcion_Promocion") %>' />
                    <br />Descuento_Promocion:
                    <asp:TextBox ID="Descuento_PromocionTextBox" runat="server" Text='<%# Bind("Descuento_Promocion") %>' />
                    <br />Url_imagen:
                    <asp:TextBox ID="Url_imagenTextBox" runat="server" Text='<%# Bind("Url_imagen") %>' />
                    <br />
                    <asp:Button ID="UpdateButton" runat="server" CommandName="Update" Text="Actualizar" />
                    <br />
                    <asp:Button ID="CancelButton" runat="server" CommandName="Cancel" Text="Cancelar" />
                    <br /></td>
            </EditItemTemplate>
            <EmptyDataTemplate>
                <table runat="server" style="background-color: #FFFFFF;border-collapse: collapse;border-color: #999999;border-style:none;border-width:1px;">
                    <tr>
                        <td>No se han devuelto datos.</td>
                    </tr>
                </table>
            </EmptyDataTemplate>
            <EmptyItemTemplate>
<td runat="server" />
            </EmptyItemTemplate>
            <GroupTemplate>
                <tr id="itemPlaceholderContainer" runat="server">
                    <td id="itemPlaceholder" runat="server"></td>
                </tr>
            </GroupTemplate>
            <InsertItemTemplate>
                <td runat="server" style="">ID_Promocion:
                    <asp:TextBox ID="ID_PromocionTextBox" runat="server" Text='<%# Bind("ID_Promocion") %>' />
                    <br />Estado_Promocion:
                    <asp:TextBox ID="Estado_PromocionTextBox0" runat="server" Text='<%# Bind("Estado_Promocion") %>' />
                    <br />Nombre_Promocion:
                    <asp:TextBox ID="Nombre_PromocionTextBox0" runat="server" Text='<%# Bind("Nombre_Promocion") %>' />
                    <br />Descripcion_Promocion:
                    <asp:TextBox ID="Descripcion_PromocionTextBox0" runat="server" Text='<%# Bind("Descripcion_Promocion") %>' />
                    <br />Descuento_Promocion:
                    <asp:TextBox ID="Descuento_PromocionTextBox0" runat="server" Text='<%# Bind("Descuento_Promocion") %>' />
                    <br />Url_imagen:
                    <asp:TextBox ID="Url_imagenTextBox0" runat="server" Text='<%# Bind("Url_imagen") %>' />
                    <br />
                    <asp:Button ID="InsertButton" runat="server" CommandName="Insert" Text="Insertar" />
                    <br />
                    <asp:Button ID="CancelButton0" runat="server" CommandName="Cancel" Text="Borrar" />
                    <br /></td>
            </InsertItemTemplate>
            <ItemTemplate>
                <td runat="server" style="background-color:#FFFFFF; color: #000000; font-size: small;" class="text-center">
                    <asp:Label ID="Nombre_PromocionLabel" runat="server" Text='<%# Eval("Nombre_Promocion") %>' Font-Bold="True" />
                    <br />
                    <asp:Label ID="Descripcion_PromocionLabel" runat="server" Text='<%# Eval("Descripcion_Promocion") %>' Font-Size="X-Small" />
                    <br />
                    <asp:Image ID="imgPromocion" runat="server" Height="150px" ImageUrl='<%# Eval("Url_imagen") %>' Width="150px" />
                    <br />
                    <br />
                    <asp:TextBox ID="txtPromocion" runat="server" CssClass="auto-style14" Width="150px"></asp:TextBox>
                    <br />
                    <asp:Button ID="btnValidar" runat="server" Text="Validar" CssClass="auto-style14" Font-Size="9pt" Width="70px" />
                    <br /></td>
            </ItemTemplate>
            <LayoutTemplate>
                <table runat="server">
                    <tr runat="server">
                        <td runat="server">
                            <table id="groupPlaceholderContainer" runat="server" border="1" style="background-color: #FFFFFF;border-collapse: collapse;border-color: #999999;border-style:none;border-width:1px;font-family: Verdana, Arial, Helvetica, sans-serif;">
                                <tr id="groupPlaceholder" runat="server">
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr runat="server">
                        <td runat="server" style="text-align: center;background-color: #CCCCCC;font-family: Verdana, Arial, Helvetica, sans-serif;color: #000000;">
                            <asp:DataPager ID="DataPager1" runat="server" PageSize="5">
                                <Fields>
                                    <asp:NextPreviousPagerField ButtonType="Button" ShowFirstPageButton="True" ShowNextPageButton="False" ShowPreviousPageButton="False" />
                                    <asp:NumericPagerField />
                                    <asp:NextPreviousPagerField ButtonType="Button" ShowLastPageButton="True" ShowNextPageButton="False" ShowPreviousPageButton="False" />
                                </Fields>
                            </asp:DataPager>
                        </td>
                    </tr>
                </table>
            </LayoutTemplate>
            <SelectedItemTemplate>
                <td runat="server" style="background-color:#008A8C;font-weight: bold;color: #FFFFFF;">ID_Promocion:
                    <asp:Label ID="ID_PromocionLabel" runat="server" Text='<%# Eval("ID_Promocion") %>' />
                    <br />Estado_Promocion:
                    <asp:Label ID="Estado_PromocionLabel" runat="server" Text='<%# Eval("Estado_Promocion") %>' />
                    <br />Nombre_Promocion:
                    <asp:Label ID="Nombre_PromocionLabel0" runat="server" Text='<%# Eval("Nombre_Promocion") %>' />
                    <br />Descripcion_Promocion:
                    <asp:Label ID="Descripcion_PromocionLabel0" runat="server" Text='<%# Eval("Descripcion_Promocion") %>' />
                    <br />Descuento_Promocion:
                    <asp:Label ID="Descuento_PromocionLabel" runat="server" Text='<%# Eval("Descuento_Promocion") %>' />
                    <br />Url_imagen:
                    <asp:Label ID="Url_imagenLabel" runat="server" Text='<%# Eval("Url_imagen") %>' />
                    <br /></td>
            </SelectedItemTemplate>
        </asp:ListView>
    <br />
    </span><span class="auto-style15">
    <span class="auto-style7"><strong style="font-size: x-large; font-weight: bold">Candy</strong></span></span><asp:ListView ID="ListView1" runat="server" DataKeyNames="ID_Articulo" DataSourceID="SqlDataSourceArticulos" GroupItemCount="7">
        <EditItemTemplate>
            <td runat="server" style="background-color:#008A8C;color: #FFFFFF;">ID_Articulo:
                <asp:Label ID="ID_ArticuloLabel1" runat="server" Text='<%# Eval("ID_Articulo") %>' />
                <br />Estado_Articulo:
                <asp:TextBox ID="Estado_ArticuloTextBox" runat="server" Text='<%# Bind("Estado_Articulo") %>' />
                <br />Nombre_Articulo:
                <asp:TextBox ID="Nombre_ArticuloTextBox" runat="server" Text='<%# Bind("Nombre_Articulo") %>' />
                <br />Descripción_Articulo:
                <asp:TextBox ID="Descripción_ArticuloTextBox" runat="server" Text='<%# Bind("Descripción_Articulo") %>' />
                <br />Precio:
                <asp:TextBox ID="PrecioTextBox" runat="server" Text='<%# Bind("Precio") %>' />
                <br />URL_Articulo:
                <asp:TextBox ID="URL_ArticuloTextBox" runat="server" Text='<%# Bind("URL_Articulo") %>' />
                <br />
                <asp:Button ID="UpdateButton" runat="server" CommandName="Update" Text="Actualizar" />
                <br />
                <asp:Button ID="CancelButton" runat="server" CommandName="Cancel" Text="Cancelar" />
                <br /></td>
        </EditItemTemplate>
        <EmptyDataTemplate>
            <table runat="server" style="background-color: #FFFFFF;border-collapse: collapse;border-color: #999999;border-style:none;border-width:1px;">
                <tr>
                    <td>No se han devuelto datos.</td>
                </tr>
            </table>
        </EmptyDataTemplate>
        <EmptyItemTemplate>
<td runat="server" />
        </EmptyItemTemplate>
        <GroupTemplate>
            <tr id="itemPlaceholderContainer" runat="server">
                <td id="itemPlaceholder" runat="server"></td>
            </tr>
        </GroupTemplate>
        <InsertItemTemplate>
            <td runat="server" style="">ID_Articulo:
                <asp:TextBox ID="ID_ArticuloTextBox" runat="server" Text='<%# Bind("ID_Articulo") %>' />
                <br />Estado_Articulo:
                <asp:TextBox ID="Estado_ArticuloTextBox" runat="server" Text='<%# Bind("Estado_Articulo") %>' />
                <br />Nombre_Articulo:
                <asp:TextBox ID="Nombre_ArticuloTextBox" runat="server" Text='<%# Bind("Nombre_Articulo") %>' />
                <br />Descripción_Articulo:
                <asp:TextBox ID="Descripción_ArticuloTextBox" runat="server" Text='<%# Bind("Descripción_Articulo") %>' />
                <br />Precio:
                <asp:TextBox ID="PrecioTextBox" runat="server" Text='<%# Bind("Precio") %>' />
                <br />URL_Articulo:
                <asp:TextBox ID="URL_ArticuloTextBox" runat="server" Text='<%# Bind("URL_Articulo") %>' />
                <br />
                <asp:Button ID="InsertButton" runat="server" CommandName="Insert" Text="Insertar" />
                <br />
                <asp:Button ID="CancelButton" runat="server" CommandName="Cancel" Text="Borrar" />
                <br /></td>
        </InsertItemTemplate>
        <ItemTemplate>
            <td runat="server" style="background-color:#FFFFFF; color: #000000; text-align: center; font-size: small;">
                <asp:Label ID="Nombre_ArticuloLabel" runat="server" Font-Bold="True" Font-Size="Small" Text='<%# Eval("Nombre_Articulo") %>'></asp:Label>
                <br />
                <asp:Label ID="Descripción_ArticuloLabel" runat="server" Text='<%# Eval("Descripción_Articulo") %>'></asp:Label>
                <br />
                Precio: $
                <asp:Label ID="PrecioLabel" runat="server" Text='<%# Eval("Precio") %>'></asp:Label>
                <br />
                <asp:Image ID="Image2" runat="server" Height="150px" ImageUrl='<%# Eval("URL_Articulo") %>' Width="150px" />
                <br />
                <br />
                <asp:DropDownList ID="ddlcantidad" runat="server" CssClass="auto-style13" Font-Size="Small">
                    <asp:ListItem Value="1"></asp:ListItem>
                    <asp:ListItem Value="2"></asp:ListItem>
                </asp:DropDownList>
                <br />
                <asp:Button ID="btnAgregar0" runat="server" CssClass="auto-style13" Font-Size="9pt" Text="Agregar" />
                <br /></td>
        </ItemTemplate>
        <LayoutTemplate>
            <table runat="server">
                <tr runat="server">
                    <td runat="server">
                        <table id="groupPlaceholderContainer" runat="server" border="1" style="background-color: #FFFFFF;border-collapse: collapse;border-color: #999999;border-style:none;border-width:1px;font-family: Verdana, Arial, Helvetica, sans-serif;">
                            <tr id="groupPlaceholder" runat="server">
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr runat="server">
                    <td runat="server" style="text-align: center;background-color: #CCCCCC;font-family: Verdana, Arial, Helvetica, sans-serif;color: #000000;">
                        <asp:DataPager ID="DataPager1" runat="server" PageSize="7">
                            <Fields>
                                <asp:NextPreviousPagerField ButtonType="Button" ShowFirstPageButton="True" ShowNextPageButton="False" ShowPreviousPageButton="False" />
                                <asp:NumericPagerField />
                                <asp:NextPreviousPagerField ButtonType="Button" ShowLastPageButton="True" ShowNextPageButton="False" ShowPreviousPageButton="False" />
                            </Fields>
                        </asp:DataPager>
                    </td>
                </tr>
            </table>
        </LayoutTemplate>
        <SelectedItemTemplate>
            <td runat="server" style="background-color:#008A8C;font-weight: bold;color: #FFFFFF;">ID_Articulo:
                <asp:Label ID="ID_ArticuloLabel" runat="server" Text='<%# Eval("ID_Articulo") %>' />
                <br />Estado_Articulo:
                <asp:Label ID="Estado_ArticuloLabel" runat="server" Text='<%# Eval("Estado_Articulo") %>' />
                <br />Nombre_Articulo:
                <asp:Label ID="Nombre_ArticuloLabel" runat="server" Text='<%# Eval("Nombre_Articulo") %>' />
                <br />Descripción_Articulo:
                <asp:Label ID="Descripción_ArticuloLabel" runat="server" Text='<%# Eval("Descripción_Articulo") %>' />
                <br />Precio:
                <asp:Label ID="PrecioLabel" runat="server" Text='<%# Eval("Precio") %>' />
                <br />URL_Articulo:
                <asp:Label ID="URL_ArticuloLabel" runat="server" Text='<%# Eval("URL_Articulo") %>' />
                <br /></td>
        </SelectedItemTemplate>
    </asp:ListView>
    <br />
    </span> 
    <span class="auto-style9"><span class="auto-style8">Articulos seleccionados:<br />
                <asp:GridView ID="gvArticulos" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataSourceID="SqlDataSourceArticulosSeleccionados" ForeColor="Black" GridLines="Horizontal" Width="503px" Font-Size="X-Small" HorizontalAlign="Center">
                    <Columns>
                        <asp:BoundField DataField="Nombre_Articulo" HeaderText="Articulo" SortExpression="Nombre_Articulo" >
                        <HeaderStyle HorizontalAlign="Center" />
                        <ItemStyle Font-Size="Small" HorizontalAlign="Left" />
                        </asp:BoundField>
                        <asp:BoundField DataField="Descripción_Articulo" HeaderText="Descripción" SortExpression="Descripción_Articulo" >
                        <HeaderStyle HorizontalAlign="Center" />
                        <ItemStyle Font-Size="Small" HorizontalAlign="Center" />
                        </asp:BoundField>
                        <asp:BoundField DataField="Cantidad" HeaderText="Cantidad" SortExpression="Cantidad" >
                        <HeaderStyle HorizontalAlign="Center" />
                        <ItemStyle Font-Size="Small" HorizontalAlign="Center" />
                        </asp:BoundField>
                        <asp:BoundField DataField="Precio" HeaderText="Precio" SortExpression="Precio" >
                        <HeaderStyle HorizontalAlign="Center" />
                        <ItemStyle Font-Size="Small" HorizontalAlign="Center" />
                        </asp:BoundField>
                    </Columns>
                    <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                    <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                    <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F7F7F7" />
                    <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                    <SortedDescendingCellStyle BackColor="#E5E5E5" />
                    <SortedDescendingHeaderStyle BackColor="#242121" />
                </asp:GridView>
            <br />
    <table class="w-100">
        <tr>
            <td class="text-center"><span __designer:mapid="282" class="auto-style18">
    <span class="auto-style9"><span class="auto-style8">
                <asp:Button ID="btnFinalizar" runat="server" CssClass="auto-style6" Text="Finalizar Compra" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Button ID="btnCancelar" runat="server" CssClass="auto-style6" Text="Cancelar" />
                </span>
    </span> </span></td>
        </tr>
    </table>
    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
    </span> </span><span class="auto-style7">
    <br />
    </span>
    <asp:SqlDataSource ID="SqlDataSourceAsientosDisponibles" runat="server" ConnectionString="<%$ ConnectionStrings:CinetecaConnectionString %>" SelectCommand="SP_AsientosDisponible" SelectCommandType="StoredProcedure">
        <SelectParameters>
            <asp:Parameter DefaultValue="0001" Name="Sala" Type="String" />
            <asp:Parameter DefaultValue="0001" Name="Sucursal" Type="String" />
            <asp:Parameter DefaultValue="m1thor" Name="Funcion" Type="String" />
            <asp:Parameter DbType="Date" DefaultValue="2020-06-10" Name="Fecha" />
        </SelectParameters>
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceAsientosReservados" runat="server" ConnectionString="<%$ ConnectionStrings:CinetecaConnectionString %>" SelectCommand="SP_AsientosReservado" SelectCommandType="StoredProcedure">
        <SelectParameters>
            <asp:Parameter DefaultValue="Reservado" Name="Estado" Type="String" />
        </SelectParameters>
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceArticulos" runat="server" ConnectionString="<%$ ConnectionStrings:CinetecaConnectionString %>" SelectCommand="SELECT * FROM [Articulos]"></asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceArticulosSeleccionados" runat="server" ConnectionString="<%$ ConnectionStrings:CinetecaConnectionString %>" SelectCommand="SP_ArticulosSeleccionados" SelectCommandType="StoredProcedure"></asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourcePromociones" runat="server" ConnectionString="<%$ ConnectionStrings:CinetecaConnectionString %>" SelectCommand="SELECT * FROM [Promociones]"></asp:SqlDataSource>
    <br />
</asp:Content>
