<%@ Page Title="" Language="C#" MasterPageFile="~/Administrador.Master" AutoEventWireup="true" CodeBehind="peliculas_alta.aspx.cs" Inherits="Vistas.peliculas_alta" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    
    <link rel="stylesheet" type="text/css" href="css/Alta.css" />
    
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Contenido" runat="server">
    <div class="contenido">
        <section class="registro">
            <h4>Agregar película</h4>
            <asp:TextBox Class="controles" runat="server" name="id" placeholder="ID"  ID="txt_id_peli"></asp:TextBox>
            <asp:TextBox Class="controles" runat="server" name="estado" placeholder="Estado"  ID="txt_estado_peli"></asp:TextBox>
            <asp:TextBox Class="controles" runat="server" name="titulo" placeholder="Título"  ID="txt_titulo_peli"></asp:TextBox>
            <asp:TextBox Class="controles" runat="server" name="duracion" placeholder="Duración"  ID="txt_duracion_peli"></asp:TextBox>
            <asp:TextBox Class="controles" runat="server" name="clasif" placeholder="Calsificaci+on"  ID="txt_clasif_peli"></asp:TextBox>
            <asp:TextBox Class="controles" runat="server" name="url" placeholder="imagenes/peliculas/titulo.jpg" ID="txt_url_peli"></asp:TextBox>
            <asp:Button  ID="btnAgregar" runat="server" Text="Agregar" Class="botons" OnClick="btnAgregar_Click" />
        </section>
        <div class="filtro-p">
               <div class="item"><asp:TextBox  runat="server" placeholder="Ingrese una película" Class="input" ID="txt_peli"></asp:TextBox></div>                              
             <div class="btn-item">
                 <asp:Button ID="btnBuscar" runat="server" OnClick="Buscar_Click" Text="Buscar" Class="boton" /> 
                 <asp:Button ID="Volver" runat="server" OnClick="Volver_Click" Text="Volver" Class="boton" />   
            </div> 
           </div> 
        <div class="listaPelis">  
            <asp:GridView ID="grdPelis" class="grid" runat="server" AllowPaging="True" OnPageIndexChanging="grdPelis_PageIndexChanging1" PageSize="6" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" AutoGenerateEditButton="True" OnRowDeleting="grdPelis_RowDeleting"  OnRowCancelingEdit="grdPelis_RowCancelingEdit" OnRowEditing="grdPelis_RowEditing" OnRowUpdating="grdPelis_RowUpdating">
                <AlternatingRowStyle CssClass="alt" />
                <Columns>
                        <asp:TemplateField HeaderText="ID Pelicula">
                            <EditItemTemplate>
                                <asp:Label ID="lbl_id_peicula" runat="server" Text='<%# Bind("[Pelicula]") %>'></asp:Label>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbl_id_peicula" runat="server" Text='<%# Bind("[Pelicula]") %>'></asp:Label>
                            </ItemTemplate>

                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Estado">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_estado_peli" runat="server" Text='<%# Bind("[Estado]") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:TextBox ID="txt_estado_peli" runat="server" Text='<%# Bind("[Estado]") %>'></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Título">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_titulo" runat="server" Text='<%# Bind("[Título]") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:TextBox ID="txt_titulo" runat="server" Text='<%# Bind("[Título]") %>'></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Duración">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_duracion" runat="server" Text='<%# Bind("[Duración]") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:TextBox ID="txt_duracion" runat="server" Text='<%# Bind("[Duración]") %>'></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                    <asp:TemplateField HeaderText="Clasificación">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_clasificacion" runat="server" Text='<%# Bind("[Clasificación]") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:TextBox ID="txt_clasificacion" runat="server" Text='<%# Bind("[Clasificación]") %>'></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                    <asp:TemplateField HeaderText="Url imagen">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_imagen" runat="server" Text='<%# Bind("[Url imagen]") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:TextBox ID="txt_imagen" runat="server" Text='<%# Bind("[Url imagen]") %>'></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
            </asp:GridView>

            
            </div>
   
    </div>
        
</asp:Content>
